name: openapi_mock

packages:
  - packages/**

scripts:
  bootstrap:
    run: melos bootstrap
    description: Install dependencies in all packages.

  analyze:
    run: melos exec -c 1 -- dart analyze
    description: Run static analysis for all packages.

  test:
    run: melos exec -c 1 -- dart test
    description: Run tests for all packages.

  test:coverage:
    run: melos exec -c 1 -- dart test --coverage=coverage
    description: Run tests with coverage output for all packages.

  format:
    run: melos exec -c 1 -- dart format .
    description: Format source files in all packages.
